[2015-06-29 12:35:17] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Rute' not found' in D:\websites\IntranetAPI\app\Http\routes.php:27
Stack trace:
#0 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(131): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(40): ()
#4 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): App\Providers\RouteServiceProvider->App\Providers\{closure}()
#5 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): call_user_func:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php:352}()
#6 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(41): Illuminate\Routing\Router->group()
#7 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->map()
#8 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#9 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(68): Illuminate\Container\Container->call()
#10 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#11 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(25): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot()
#12 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->boot()
#13 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#14 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(703): Illuminate\Container\Container->call()
#15 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(685): Illuminate\Foundation\Application->bootProvider()
#16 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#17 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): array_walk()
#18 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(15): Illuminate\Foundation\Application->boot()
#19 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(183): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#20 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(199): Illuminate\Foundation\Application->bootstrapWith()
#21 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->bootstrap()
#22 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#23 D:\websites\IntranetAPI\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle()
#24 D:\websites\IntranetAPI\public\index.php(0): {main}()
#25 {main}  
[2015-06-29 12:35:26] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Rute' not found' in D:\websites\IntranetAPI\app\Http\routes.php:27
Stack trace:
#0 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(131): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(40): ()
#4 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): App\Providers\RouteServiceProvider->App\Providers\{closure}()
#5 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): call_user_func:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php:352}()
#6 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(41): Illuminate\Routing\Router->group()
#7 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->map()
#8 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#9 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(68): Illuminate\Container\Container->call()
#10 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#11 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(25): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot()
#12 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->boot()
#13 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#14 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(703): Illuminate\Container\Container->call()
#15 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(685): Illuminate\Foundation\Application->bootProvider()
#16 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#17 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): array_walk()
#18 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(15): Illuminate\Foundation\Application->boot()
#19 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(183): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#20 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(199): Illuminate\Foundation\Application->bootstrapWith()
#21 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->bootstrap()
#22 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#23 D:\websites\IntranetAPI\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle()
#24 D:\websites\IntranetAPI\public\index.php(0): {main}()
#25 {main}  
[2015-06-29 13:33:55] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=>' (T_DOUBLE_ARROW)' in D:\websites\IntranetAPI\app\Http\routes.php:27
Stack trace:
#0 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(131): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): App\Providers\RouteServiceProvider->App\Providers\{closure}()
#4 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): call_user_func:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php:352}()
#5 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(41): Illuminate\Routing\Router->group()
#6 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->map()
#7 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#8 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(68): Illuminate\Container\Container->call()
#9 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#10 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(25): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot()
#11 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->boot()
#12 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#13 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(703): Illuminate\Container\Container->call()
#14 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(685): Illuminate\Foundation\Application->bootProvider()
#15 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#16 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): array_walk()
#17 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(15): Illuminate\Foundation\Application->boot()
#18 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(183): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#19 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(199): Illuminate\Foundation\Application->bootstrapWith()
#20 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->bootstrap()
#21 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#22 D:\websites\IntranetAPI\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle()
#23 D:\websites\IntranetAPI\public\index.php(0): {main}()
#24 {main}  
[2015-06-29 13:34:33] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=>' (T_DOUBLE_ARROW)' in D:\websites\IntranetAPI\app\Http\routes.php:27
Stack trace:
#0 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(131): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): App\Providers\RouteServiceProvider->App\Providers\{closure}()
#4 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): call_user_func:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php:352}()
#5 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(41): Illuminate\Routing\Router->group()
#6 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->map()
#7 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#8 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(68): Illuminate\Container\Container->call()
#9 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#10 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(25): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot()
#11 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->boot()
#12 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#13 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(703): Illuminate\Container\Container->call()
#14 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(685): Illuminate\Foundation\Application->bootProvider()
#15 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#16 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): array_walk()
#17 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(15): Illuminate\Foundation\Application->boot()
#18 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(183): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#19 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(199): Illuminate\Foundation\Application->bootstrapWith()
#20 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->bootstrap()
#21 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#22 D:\websites\IntranetAPI\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle()
#23 D:\websites\IntranetAPI\public\index.php(0): {main}()
#24 {main}  
[2015-06-29 13:34:53] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=>' (T_DOUBLE_ARROW)' in D:\websites\IntranetAPI\app\Http\routes.php:27
Stack trace:
#0 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(131): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): App\Providers\RouteServiceProvider->App\Providers\{closure}()
#4 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): call_user_func:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php:352}()
#5 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(41): Illuminate\Routing\Router->group()
#6 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->map()
#7 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#8 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(68): Illuminate\Container\Container->call()
#9 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#10 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(25): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot()
#11 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->boot()
#12 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#13 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(703): Illuminate\Container\Container->call()
#14 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(685): Illuminate\Foundation\Application->bootProvider()
#15 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#16 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): array_walk()
#17 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(15): Illuminate\Foundation\Application->boot()
#18 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(183): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#19 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(199): Illuminate\Foundation\Application->bootstrapWith()
#20 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->bootstrap()
#21 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#22 D:\websites\IntranetAPI\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle()
#23 D:\websites\IntranetAPI\public\index.php(0): {main}()
#24 {main}  
[2015-06-29 13:35:11] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=>' (T_DOUBLE_ARROW)' in D:\websites\IntranetAPI\app\Http\routes.php:27
Stack trace:
#0 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(131): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): App\Providers\RouteServiceProvider->App\Providers\{closure}()
#4 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): call_user_func:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php:352}()
#5 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(41): Illuminate\Routing\Router->group()
#6 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->map()
#7 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#8 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(68): Illuminate\Container\Container->call()
#9 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#10 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(25): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot()
#11 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->boot()
#12 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#13 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(703): Illuminate\Container\Container->call()
#14 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(685): Illuminate\Foundation\Application->bootProvider()
#15 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#16 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): array_walk()
#17 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(15): Illuminate\Foundation\Application->boot()
#18 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(183): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#19 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(199): Illuminate\Foundation\Application->bootstrapWith()
#20 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->bootstrap()
#21 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#22 D:\websites\IntranetAPI\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle()
#23 D:\websites\IntranetAPI\public\index.php(0): {main}()
#24 {main}  
[2015-06-29 13:35:35] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=>' (T_DOUBLE_ARROW)' in D:\websites\IntranetAPI\app\Http\routes.php:27
Stack trace:
#0 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(131): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): App\Providers\RouteServiceProvider->App\Providers\{closure}()
#4 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): call_user_func:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php:352}()
#5 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(41): Illuminate\Routing\Router->group()
#6 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->map()
#7 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#8 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(68): Illuminate\Container\Container->call()
#9 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#10 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(25): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot()
#11 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->boot()
#12 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#13 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(703): Illuminate\Container\Container->call()
#14 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(685): Illuminate\Foundation\Application->bootProvider()
#15 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#16 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): array_walk()
#17 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(15): Illuminate\Foundation\Application->boot()
#18 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(183): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#19 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(199): Illuminate\Foundation\Application->bootstrapWith()
#20 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->bootstrap()
#21 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#22 D:\websites\IntranetAPI\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle()
#23 D:\websites\IntranetAPI\public\index.php(0): {main}()
#24 {main}  
[2015-06-29 13:36:14] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Rute' not found' in D:\websites\IntranetAPI\app\Http\routes.php:27
Stack trace:
#0 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(131): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(40): ()
#4 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): App\Providers\RouteServiceProvider->App\Providers\{closure}()
#5 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(352): call_user_func:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php:352}()
#6 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(41): Illuminate\Routing\Router->group()
#7 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->map()
#8 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#9 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(68): Illuminate\Container\Container->call()
#10 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#11 D:\websites\IntranetAPI\app\Providers\RouteServiceProvider.php(25): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot()
#12 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): App\Providers\RouteServiceProvider->boot()
#13 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php(526): call_user_func_array:{D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Container\Container.php:526}()
#14 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(703): Illuminate\Container\Container->call()
#15 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(685): Illuminate\Foundation\Application->bootProvider()
#16 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#17 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(686): array_walk()
#18 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(15): Illuminate\Foundation\Application->boot()
#19 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(183): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#20 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(199): Illuminate\Foundation\Application->bootstrapWith()
#21 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->bootstrap()
#22 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#23 D:\websites\IntranetAPI\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle()
#24 D:\websites\IntranetAPI\public\index.php(0): {main}()
#25 {main}  
[2015-06-29 13:36:39] local.ERROR: exception 'UnexpectedValueException' with message 'The Response content must be a string or object implementing __toString(), "boolean" given.' in D:\websites\IntranetAPI\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php:403
Stack trace:
#0 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Http\Response.php(47): Symfony\Component\HttpFoundation\Response->setContent(true)
#1 D:\websites\IntranetAPI\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(202): Illuminate\Http\Response->setContent(true)
#2 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1198): Symfony\Component\HttpFoundation\Response->__construct(true)
#3 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(702): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), true)
#4 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#5 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#6 D:\websites\IntranetAPI\app\Http\Middleware\OnceAuth.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#7 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): App\Http\Middleware\OnceAuth->handle(Object(Illuminate\Http\Request), Object(Closure))
#8 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#12 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#15 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#30 D:\websites\IntranetAPI\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#31 {main}  
[2015-06-29 13:42:09] local.ERROR: exception 'UnexpectedValueException' with message 'The Response content must be a string or object implementing __toString(), "boolean" given.' in D:\websites\IntranetAPI\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php:403
Stack trace:
#0 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Http\Response.php(47): Symfony\Component\HttpFoundation\Response->setContent(true)
#1 D:\websites\IntranetAPI\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(202): Illuminate\Http\Response->setContent(true)
#2 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1198): Symfony\Component\HttpFoundation\Response->__construct(true)
#3 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(702): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), true)
#4 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#5 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#6 D:\websites\IntranetAPI\app\Http\Middleware\OnceAuth.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#7 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): App\Http\Middleware\OnceAuth->handle(Object(Illuminate\Http\Request), Object(Closure))
#8 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#12 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#15 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 D:\websites\IntranetAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#30 D:\websites\IntranetAPI\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#31 {main}  
